version: '2'
services:
  sol_status_bot:
    image: derzwerggimli/solana_tps_bot:latest
    restart: always
    environment:
      - RUST_LOG=${RUST_LOG}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - LOOP_UPDATE_SLEEP=${LOOP_UPDATE_SLEEP}
      - TPS_THRESHOLD=${TPS_THRESHOLD}
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
